name: Save Today Word

on:
  schedule:
    # Runs at 22:45 UTC (23:45 CET/CEST)
    - cron: '45 22 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  save-today-word:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libasound2 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            libxss1 \
            libgbm1
            
      - name: Install Puppeteer (with Chrome)
        run: deno install --allow-scripts=npm:puppeteer@24.11.2

      - name: Run save-today-word
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: deno task prod-cron:save-today-word
