name: Send Word Info

on:
  schedule:
    # Runs at 07:00 UTC (08:00 CET/CEST)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  send-word-info:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Puppeteer (with Chrome)
        run: deno install --allow-scripts=npm:puppeteer@24.11.2

      - name: Run send-word-info
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: deno task prod-cron:send-word-info
